<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jh_magnificpopup_animation"
 *
 * Auto generated by Extension Builder 2014-10-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Magnific Popup - Animation Effects',
	'description' => 'This extension provides some animation effects for MagnificPopup from EXT:jh_magnificpopup',
	'category' => 'plugin',
	'author' => 'Jonathan Heilmann',
	'author_email' => 'mail@jonathan-heilmann.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => false,
	'createDirs' => '',
	'clearCacheOnLoad' => false,
	'version' => '0.4.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
			'jh_magnificpopup' => '0.4.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);